# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: metric-exporter-ds
    app.kubernetes.io/version: v0.0.1
  name: metric-exporter-ds
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metric-exporter-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metric-exporter-ds
        app.kubernetes.io/version: v0.0.1
    spec:
      priorityClassName: "system-node-critical"
      imagePullSecrets: []
      tolerations:
      - key: "habana.ai/gaudi"
        operator: "Exists"
        effect: "NoSchedule"
      # Required for network monitoring
      hostNetwork: true
      containers:
      - name: metric-exporter
        image: vault.habana.ai/gaudi-metric-exporter/metric-exporter:1.18.0-524
        imagePullPolicy: Always
        env:
        - name: LD_LIBRARY_PATH
          value: "/usr/lib/habanalabs"
        securityContext:
          privileged: true
        volumeMounts:
          - name: pod-resources
            mountPath: /var/lib/kubelet/pod-resources
        ports:
        - name: habana-metrics
          containerPort: 41611
          protocol: TCP
        resources:
          limits:
            cpu: 150m
            memory: 120Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
        - name: pod-resources
          hostPath:
            path: /var/lib/kubelet/pod-resources

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: metric-exporter
    app.kubernetes.io/version: v0.0.1
  name: metric-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: habana-metrics
    port: 41611
  selector:
    app.kubernetes.io/name: metric-exporter-ds

# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   labels:
#     app.kubernetes.io/name: metric-exporter
#     app.kubernetes.io/version: v0.0.1
#   name: metric-exporter
#   namespace: monitoring
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: metric-exporter
#   endpoints:
#   - port: habana-metrics
#     interval: 30s
